[uWSGI] getting INI configuration from /root/Project/jianshu/uwsgi.ini
*** Starting uWSGI 2.0.18 (64bit) on [Sun Apr 26 20:31:50 2020] ***
compiled with version: 8.3.0 on 26 April 2020 05:14:19
os: Linux-4.19.0-8-amd64 #1 SMP Debian 4.19.98-1 (2020-01-26)
nodename: Debian
machine: x86_64
clock source: unix
detected number of CPU cores: 1
current working directory: /root/Project/jianshu
detected binary path: /root/VENV/bin/uwsgi
!!! no internal routing support, rebuild with pcre support !!!
uWSGI running as root, you can use --uid/--gid/--chroot options
*** WARNING: you are running uWSGI as root !!! (use the --uid flag) *** 
your processes number limit is 3727
your memory page size is 4096 bytes
detected max file descriptor number: 1048576
lock engine: pthread robust mutexes
thunder lock: disabled (you can enable it with --thunder-lock)
uwsgi socket 0 bound to TCP address :1024 fd 3
uWSGI running as root, you can use --uid/--gid/--chroot options
*** WARNING: you are running uWSGI as root !!! (use the --uid flag) *** 
Python version: 3.7.3 (default, Dec 20 2019, 18:57:59)  [GCC 8.3.0]
PEP 405 virtualenv detected: /root/VENV
Set PythonHome to /root/VENV
Python main interpreter initialized at 0x55a65ca75650
uWSGI running as root, you can use --uid/--gid/--chroot options
*** WARNING: you are running uWSGI as root !!! (use the --uid flag) *** 
python threads support enabled
your server socket listen backlog is limited to 100 connections
your mercy for graceful operations on workers is 60 seconds
mapped 145808 bytes (142 KB) for 1 cores
*** Operational MODE: single process ***
WSGI app 0 (mountpoint='') ready in 1 seconds on interpreter 0x55a65ca75650 pid: 5519 (default app)
uWSGI running as root, you can use --uid/--gid/--chroot options
*** WARNING: you are running uWSGI as root !!! (use the --uid flag) *** 
*** uWSGI is running in multiple interpreter mode ***
spawned uWSGI master process (pid: 5519)
spawned uWSGI worker 1 (pid: 5520, cores: 1)
Python auto-reloader enabled
[uwsgi-python-reloader] module/file /root/Project/jianshu/app.py has been modified
...gracefully killing workers...
Gracefully killing worker 1 (pid: 5520)...
worker 1 buried after 2 seconds
binary reloading uWSGI...
chdir() to /root/Project/jianshu
closing all non-uwsgi socket fds > 2 (max_fd = 1048576)...
found fd 3 mapped to socket 0 (:1024)
running /root/VENV/bin/uwsgi
[uWSGI] getting INI configuration from /root/Project/jianshu/uwsgi.ini
*** Starting uWSGI 2.0.18 (64bit) on [Sun Apr 26 21:08:24 2020] ***
compiled with version: 8.3.0 on 26 April 2020 05:14:19
os: Linux-4.19.0-8-amd64 #1 SMP Debian 4.19.98-1 (2020-01-26)
nodename: Debian
machine: x86_64
clock source: unix
detected number of CPU cores: 1
current working directory: /root/Project/jianshu
detected binary path: /root/VENV/bin/uwsgi
!!! no internal routing support, rebuild with pcre support !!!
uWSGI running as root, you can use --uid/--gid/--chroot options
*** WARNING: you are running uWSGI as root !!! (use the --uid flag) *** 
your processes number limit is 3727
your memory page size is 4096 bytes
detected max file descriptor number: 1048576
lock engine: pthread robust mutexes
thunder lock: disabled (you can enable it with --thunder-lock)
uwsgi socket 0 inherited INET address :1024 fd 3
uWSGI running as root, you can use --uid/--gid/--chroot options
*** WARNING: you are running uWSGI as root !!! (use the --uid flag) *** 
Python version: 3.7.3 (default, Dec 20 2019, 18:57:59)  [GCC 8.3.0]
PEP 405 virtualenv detected: /root/VENV
Set PythonHome to /root/VENV
Python main interpreter initialized at 0x5570cfd77d30
uWSGI running as root, you can use --uid/--gid/--chroot options
*** WARNING: you are running uWSGI as root !!! (use the --uid flag) *** 
python threads support enabled
your server socket listen backlog is limited to 100 connections
your mercy for graceful operations on workers is 60 seconds
mapped 145808 bytes (142 KB) for 1 cores
*** Operational MODE: single process ***
WSGI app 0 (mountpoint='') ready in 0 seconds on interpreter 0x5570cfd77d30 pid: 5519 (default app)
uWSGI running as root, you can use --uid/--gid/--chroot options
*** WARNING: you are running uWSGI as root !!! (use the --uid flag) *** 
*** uWSGI is running in multiple interpreter mode ***
gracefully (RE)spawned uWSGI master process (pid: 5519)
spawned uWSGI worker 1 (pid: 6067, cores: 1)
Python auto-reloader enabled
[uwsgi-python-reloader] module/file /root/Project/jianshu/app.py has been modified
...gracefully killing workers...
Gracefully killing worker 1 (pid: 6067)...
worker 1 buried after 1 seconds
binary reloading uWSGI...
chdir() to /root/Project/jianshu
closing all non-uwsgi socket fds > 2 (max_fd = 1048576)...
found fd 3 mapped to socket 0 (:1024)
running /root/VENV/bin/uwsgi
[uWSGI] getting INI configuration from /root/Project/jianshu/uwsgi.ini
*** Starting uWSGI 2.0.18 (64bit) on [Sun Apr 26 21:10:14 2020] ***
compiled with version: 8.3.0 on 26 April 2020 05:14:19
os: Linux-4.19.0-8-amd64 #1 SMP Debian 4.19.98-1 (2020-01-26)
nodename: Debian
machine: x86_64
clock source: unix
detected number of CPU cores: 1
current working directory: /root/Project/jianshu
detected binary path: /root/VENV/bin/uwsgi
!!! no internal routing support, rebuild with pcre support !!!
uWSGI running as root, you can use --uid/--gid/--chroot options
*** WARNING: you are running uWSGI as root !!! (use the --uid flag) *** 
your processes number limit is 3727
your memory page size is 4096 bytes
detected max file descriptor number: 1048576
lock engine: pthread robust mutexes
thunder lock: disabled (you can enable it with --thunder-lock)
uwsgi socket 0 inherited INET address :1024 fd 3
uWSGI running as root, you can use --uid/--gid/--chroot options
*** WARNING: you are running uWSGI as root !!! (use the --uid flag) *** 
Python version: 3.7.3 (default, Dec 20 2019, 18:57:59)  [GCC 8.3.0]
PEP 405 virtualenv detected: /root/VENV
Set PythonHome to /root/VENV
Python main interpreter initialized at 0x562ba232ad30
uWSGI running as root, you can use --uid/--gid/--chroot options
*** WARNING: you are running uWSGI as root !!! (use the --uid flag) *** 
python threads support enabled
your server socket listen backlog is limited to 100 connections
your mercy for graceful operations on workers is 60 seconds
mapped 145808 bytes (142 KB) for 1 cores
*** Operational MODE: single process ***
WSGI app 0 (mountpoint='') ready in 0 seconds on interpreter 0x562ba232ad30 pid: 5519 (default app)
uWSGI running as root, you can use --uid/--gid/--chroot options
*** WARNING: you are running uWSGI as root !!! (use the --uid flag) *** 
*** uWSGI is running in multiple interpreter mode ***
gracefully (RE)spawned uWSGI master process (pid: 5519)
spawned uWSGI worker 1 (pid: 6076, cores: 1)
Python auto-reloader enabled
[uwsgi-python-reloader] module/file /root/Project/jianshu/app.py has been modified
...gracefully killing workers...
Gracefully killing worker 1 (pid: 6076)...
worker 1 buried after 1 seconds
binary reloading uWSGI...
chdir() to /root/Project/jianshu
closing all non-uwsgi socket fds > 2 (max_fd = 1048576)...
found fd 3 mapped to socket 0 (:1024)
running /root/VENV/bin/uwsgi
[uWSGI] getting INI configuration from /root/Project/jianshu/uwsgi.ini
*** Starting uWSGI 2.0.18 (64bit) on [Sun Apr 26 21:10:57 2020] ***
compiled with version: 8.3.0 on 26 April 2020 05:14:19
os: Linux-4.19.0-8-amd64 #1 SMP Debian 4.19.98-1 (2020-01-26)
nodename: Debian
machine: x86_64
clock source: unix
detected number of CPU cores: 1
current working directory: /root/Project/jianshu
detected binary path: /root/VENV/bin/uwsgi
!!! no internal routing support, rebuild with pcre support !!!
uWSGI running as root, you can use --uid/--gid/--chroot options
*** WARNING: you are running uWSGI as root !!! (use the --uid flag) *** 
your processes number limit is 3727
your memory page size is 4096 bytes
detected max file descriptor number: 1048576
lock engine: pthread robust mutexes
thunder lock: disabled (you can enable it with --thunder-lock)
uwsgi socket 0 inherited INET address :1024 fd 3
uWSGI running as root, you can use --uid/--gid/--chroot options
*** WARNING: you are running uWSGI as root !!! (use the --uid flag) *** 
Python version: 3.7.3 (default, Dec 20 2019, 18:57:59)  [GCC 8.3.0]
PEP 405 virtualenv detected: /root/VENV
Set PythonHome to /root/VENV
Python main interpreter initialized at 0x55e5e6b44d30
uWSGI running as root, you can use --uid/--gid/--chroot options
*** WARNING: you are running uWSGI as root !!! (use the --uid flag) *** 
python threads support enabled
your server socket listen backlog is limited to 100 connections
your mercy for graceful operations on workers is 60 seconds
mapped 145808 bytes (142 KB) for 1 cores
*** Operational MODE: single process ***
WSGI app 0 (mountpoint='') ready in 0 seconds on interpreter 0x55e5e6b44d30 pid: 5519 (default app)
uWSGI running as root, you can use --uid/--gid/--chroot options
*** WARNING: you are running uWSGI as root !!! (use the --uid flag) *** 
*** uWSGI is running in multiple interpreter mode ***
gracefully (RE)spawned uWSGI master process (pid: 5519)
spawned uWSGI worker 1 (pid: 6084, cores: 1)
Python auto-reloader enabled
[uwsgi-python-reloader] module/file /root/Project/jianshu/app.py has been modified
...gracefully killing workers...
Gracefully killing worker 1 (pid: 6084)...
worker 1 buried after 1 seconds
binary reloading uWSGI...
chdir() to /root/Project/jianshu
closing all non-uwsgi socket fds > 2 (max_fd = 1048576)...
found fd 3 mapped to socket 0 (:1024)
running /root/VENV/bin/uwsgi
[uWSGI] getting INI configuration from /root/Project/jianshu/uwsgi.ini
*** Starting uWSGI 2.0.18 (64bit) on [Sun Apr 26 21:11:18 2020] ***
compiled with version: 8.3.0 on 26 April 2020 05:14:19
os: Linux-4.19.0-8-amd64 #1 SMP Debian 4.19.98-1 (2020-01-26)
nodename: Debian
machine: x86_64
clock source: unix
detected number of CPU cores: 1
current working directory: /root/Project/jianshu
detected binary path: /root/VENV/bin/uwsgi
!!! no internal routing support, rebuild with pcre support !!!
uWSGI running as root, you can use --uid/--gid/--chroot options
*** WARNING: you are running uWSGI as root !!! (use the --uid flag) *** 
your processes number limit is 3727
your memory page size is 4096 bytes
detected max file descriptor number: 1048576
lock engine: pthread robust mutexes
thunder lock: disabled (you can enable it with --thunder-lock)
uwsgi socket 0 inherited INET address :1024 fd 3
uWSGI running as root, you can use --uid/--gid/--chroot options
*** WARNING: you are running uWSGI as root !!! (use the --uid flag) *** 
Python version: 3.7.3 (default, Dec 20 2019, 18:57:59)  [GCC 8.3.0]
PEP 405 virtualenv detected: /root/VENV
Set PythonHome to /root/VENV
Python main interpreter initialized at 0x55cafbed2d30
uWSGI running as root, you can use --uid/--gid/--chroot options
*** WARNING: you are running uWSGI as root !!! (use the --uid flag) *** 
python threads support enabled
your server socket listen backlog is limited to 100 connections
your mercy for graceful operations on workers is 60 seconds
mapped 145808 bytes (142 KB) for 1 cores
*** Operational MODE: single process ***
Traceback (most recent call last):
  File "/root/Project/jianshu/app.py", line 19, in <module>
    @app.route('/api', method='GET')
  File "/root/VENV/lib/python3.7/site-packages/flask/app.py", line 1315, in decorator
    self.add_url_rule(rule, endpoint, f, **options)
  File "/root/VENV/lib/python3.7/site-packages/flask/app.py", line 98, in wrapper_func
    return f(self, *args, **kwargs)
  File "/root/VENV/lib/python3.7/site-packages/flask/app.py", line 1275, in add_url_rule
    rule = self.url_rule_class(rule, methods=methods, **options)
TypeError: __init__() got an unexpected keyword argument 'method'
unable to load app 0 (mountpoint='') (callable not found or import error)
*** no app loaded. going in full dynamic mode ***
uWSGI running as root, you can use --uid/--gid/--chroot options
*** WARNING: you are running uWSGI as root !!! (use the --uid flag) *** 
*** uWSGI is running in multiple interpreter mode ***
gracefully (RE)spawned uWSGI master process (pid: 5519)
spawned uWSGI worker 1 (pid: 6090, cores: 1)
Python auto-reloader enabled
SystemError: ../Objects/listobject.c:243: bad argument to internal function
Traceback (most recent call last):
  File "/root/Project/jianshu/app.py", line 19, in <module>
    @app.route('/api', method=['GET'])
  File "/root/VENV/lib/python3.7/site-packages/flask/app.py", line 1315, in decorator
    self.add_url_rule(rule, endpoint, f, **options)
  File "/root/VENV/lib/python3.7/site-packages/flask/app.py", line 98, in wrapper_func
    return f(self, *args, **kwargs)
  File "/root/VENV/lib/python3.7/site-packages/flask/app.py", line 1275, in add_url_rule
    rule = self.url_rule_class(rule, methods=methods, **options)
TypeError: __init__() got an unexpected keyword argument 'method'
unable to load app 0 (mountpoint='') (callable not found or import error)
--- no python application found, check your startup logs for errors ---
[pid: 6090|app: -1|req: -1/1] 192.168.168.1 () {48 vars in 847 bytes} [Sun Apr 26 21:11:30 2020] GET / => generated 21 bytes in 62 msecs (HTTP/1.1 500) 2 headers in 83 bytes (0 switches on core 0)
SystemError: ../Objects/listobject.c:243: bad argument to internal function
Traceback (most recent call last):
  File "/root/Project/jianshu/app.py", line 19, in <module>
    @app.route('/api', method=['GET'])
  File "/root/VENV/lib/python3.7/site-packages/flask/app.py", line 1315, in decorator
    self.add_url_rule(rule, endpoint, f, **options)
  File "/root/VENV/lib/python3.7/site-packages/flask/app.py", line 98, in wrapper_func
    return f(self, *args, **kwargs)
  File "/root/VENV/lib/python3.7/site-packages/flask/app.py", line 1275, in add_url_rule
    rule = self.url_rule_class(rule, methods=methods, **options)
TypeError: __init__() got an unexpected keyword argument 'method'
unable to load app 0 (mountpoint='') (callable not found or import error)
--- no python application found, check your startup logs for errors ---
[pid: 6090|app: -1|req: -1/2] 192.168.168.1 () {48 vars in 853 bytes} [Sun Apr 26 21:11:36 2020] GET /api => generated 21 bytes in 15 msecs (HTTP/1.1 500) 2 headers in 83 bytes (0 switches on core 0)
SystemError: ../Objects/listobject.c:243: bad argument to internal function
Traceback (most recent call last):
  File "/root/Project/jianshu/app.py", line 19, in <module>
    @app.route('/api', method=['GET'])
  File "/root/VENV/lib/python3.7/site-packages/flask/app.py", line 1315, in decorator
    self.add_url_rule(rule, endpoint, f, **options)
  File "/root/VENV/lib/python3.7/site-packages/flask/app.py", line 98, in wrapper_func
    return f(self, *args, **kwargs)
  File "/root/VENV/lib/python3.7/site-packages/flask/app.py", line 1275, in add_url_rule
    rule = self.url_rule_class(rule, methods=methods, **options)
TypeError: __init__() got an unexpected keyword argument 'method'
unable to load app 0 (mountpoint='') (callable not found or import error)
--- no python application found, check your startup logs for errors ---
[pid: 6090|app: -1|req: -1/3] 192.168.168.1 () {50 vars in 884 bytes} [Sun Apr 26 21:11:47 2020] GET /api => generated 21 bytes in 15 msecs (HTTP/1.1 500) 2 headers in 83 bytes (0 switches on core 0)
SystemError: ../Objects/listobject.c:243: bad argument to internal function
Traceback (most recent call last):
  File "/root/Project/jianshu/app.py", line 19, in <module>
    @app.route('/api', method=['GET'])
  File "/root/VENV/lib/python3.7/site-packages/flask/app.py", line 1315, in decorator
    self.add_url_rule(rule, endpoint, f, **options)
  File "/root/VENV/lib/python3.7/site-packages/flask/app.py", line 98, in wrapper_func
    return f(self, *args, **kwargs)
  File "/root/VENV/lib/python3.7/site-packages/flask/app.py", line 1275, in add_url_rule
    rule = self.url_rule_class(rule, methods=methods, **options)
TypeError: __init__() got an unexpected keyword argument 'method'
unable to load app 0 (mountpoint='') (callable not found or import error)
--- no python application found, check your startup logs for errors ---
[pid: 6090|app: -1|req: -1/4] 192.168.168.1 () {48 vars in 847 bytes} [Sun Apr 26 21:17:18 2020] GET / => generated 21 bytes in 232 msecs (HTTP/1.1 500) 2 headers in 83 bytes (0 switches on core 0)
SystemError: ../Objects/listobject.c:243: bad argument to internal function
Traceback (most recent call last):
  File "/root/Project/jianshu/app.py", line 19, in <module>
    @app.route('/api', method=['GET'])
  File "/root/VENV/lib/python3.7/site-packages/flask/app.py", line 1315, in decorator
    self.add_url_rule(rule, endpoint, f, **options)
  File "/root/VENV/lib/python3.7/site-packages/flask/app.py", line 98, in wrapper_func
    return f(self, *args, **kwargs)
  File "/root/VENV/lib/python3.7/site-packages/flask/app.py", line 1275, in add_url_rule
    rule = self.url_rule_class(rule, methods=methods, **options)
TypeError: __init__() got an unexpected keyword argument 'method'
unable to load app 0 (mountpoint='') (callable not found or import error)
--- no python application found, check your startup logs for errors ---
[pid: 6090|app: -1|req: -1/5] 192.168.168.1 () {50 vars in 878 bytes} [Sun Apr 26 21:17:20 2020] GET / => generated 21 bytes in 28 msecs (HTTP/1.1 500) 2 headers in 83 bytes (0 switches on core 0)
[uWSGI] getting INI configuration from /root/Project/jianshu/uwsgi.ini
*** Starting uWSGI 2.0.18 (64bit) on [Mon Apr 27 00:20:21 2020] ***
compiled with version: 8.3.0 on 26 April 2020 05:14:19
os: Linux-4.19.0-8-amd64 #1 SMP Debian 4.19.98-1 (2020-01-26)
nodename: Debian
machine: x86_64
clock source: unix
detected number of CPU cores: 1
current working directory: /root/Project/jianshu
detected binary path: /root/VENV/bin/uwsgi
!!! no internal routing support, rebuild with pcre support !!!
uWSGI running as root, you can use --uid/--gid/--chroot options
*** WARNING: you are running uWSGI as root !!! (use the --uid flag) *** 
your processes number limit is 3727
your memory page size is 4096 bytes
detected max file descriptor number: 1024
lock engine: pthread robust mutexes
thunder lock: disabled (you can enable it with --thunder-lock)
uwsgi socket 0 bound to TCP address :1024 fd 3
uWSGI running as root, you can use --uid/--gid/--chroot options
*** WARNING: you are running uWSGI as root !!! (use the --uid flag) *** 
Python version: 3.7.3 (default, Dec 20 2019, 18:57:59)  [GCC 8.3.0]
PEP 405 virtualenv detected: /root/VENV
Set PythonHome to /root/VENV
Python main interpreter initialized at 0x561b9fdcf750
uWSGI running as root, you can use --uid/--gid/--chroot options
*** WARNING: you are running uWSGI as root !!! (use the --uid flag) *** 
python threads support enabled
your server socket listen backlog is limited to 100 connections
your mercy for graceful operations on workers is 60 seconds
mapped 145808 bytes (142 KB) for 1 cores
*** Operational MODE: single process ***
WSGI app 0 (mountpoint='') ready in 0 seconds on interpreter 0x561b9fdcf750 pid: 981 (default app)
uWSGI running as root, you can use --uid/--gid/--chroot options
*** WARNING: you are running uWSGI as root !!! (use the --uid flag) *** 
*** uWSGI is running in multiple interpreter mode ***
spawned uWSGI master process (pid: 981)
spawned uWSGI worker 1 (pid: 982, cores: 1)
Python auto-reloader enabled
SIGINT/SIGQUIT received...killing workers...
[uWSGI] getting INI configuration from /root/Project/jianshu/uwsgi.ini
*** Starting uWSGI 2.0.18 (64bit) on [Mon Apr 27 00:20:48 2020] ***
compiled with version: 8.3.0 on 26 April 2020 05:14:19
os: Linux-4.19.0-8-amd64 #1 SMP Debian 4.19.98-1 (2020-01-26)
nodename: Debian
machine: x86_64
clock source: unix
detected number of CPU cores: 1
current working directory: /root/Project/jianshu
detected binary path: /root/VENV/bin/uwsgi
!!! no internal routing support, rebuild with pcre support !!!
uWSGI running as root, you can use --uid/--gid/--chroot options
*** WARNING: you are running uWSGI as root !!! (use the --uid flag) *** 
your processes number limit is 3727
your memory page size is 4096 bytes
detected max file descriptor number: 1024
lock engine: pthread robust mutexes
thunder lock: disabled (you can enable it with --thunder-lock)
uwsgi socket 0 bound to TCP address :1024 fd 3
uWSGI running as root, you can use --uid/--gid/--chroot options
*** WARNING: you are running uWSGI as root !!! (use the --uid flag) *** 
Python version: 3.7.3 (default, Dec 20 2019, 18:57:59)  [GCC 8.3.0]
PEP 405 virtualenv detected: /root/VENV
Set PythonHome to /root/VENV
Python main interpreter initialized at 0x563d21615750
uWSGI running as root, you can use --uid/--gid/--chroot options
*** WARNING: you are running uWSGI as root !!! (use the --uid flag) *** 
python threads support enabled
your server socket listen backlog is limited to 100 connections
your mercy for graceful operations on workers is 60 seconds
mapped 145808 bytes (142 KB) for 1 cores
*** Operational MODE: single process ***
WSGI app 0 (mountpoint='') ready in 0 seconds on interpreter 0x563d21615750 pid: 542 (default app)
uWSGI running as root, you can use --uid/--gid/--chroot options
*** WARNING: you are running uWSGI as root !!! (use the --uid flag) *** 
*** uWSGI is running in multiple interpreter mode ***
spawned uWSGI master process (pid: 542)
spawned uWSGI worker 1 (pid: 543, cores: 1)
Python auto-reloader enabled
[pid: 543|app: 0|req: 1/1] 192.168.168.1 () {50 vars in 878 bytes} [Mon Apr 27 00:21:07 2020] GET / => generated 2448 bytes in 57 msecs (HTTP/1.1 200) 2 headers in 81 bytes (1 switches on core 0)
[pid: 543|app: 0|req: 2/2] 192.168.168.1 () {48 vars in 849 bytes} [Mon Apr 27 00:21:07 2020] GET /backend/static/build/static/css/2.8d06fd47.chunk.css => generated 557511 bytes in 21 msecs via sendfile() (HTTP/1.1 200) 7 headers in 287 bytes (0 switches on core 0)
[pid: 543|app: 0|req: 3/3] 192.168.168.1 () {48 vars in 855 bytes} [Mon Apr 27 00:21:07 2020] GET /backend/static/build/static/css/main.a44b53bb.chunk.css => generated 453 bytes in 7 msecs via sendfile() (HTTP/1.1 200) 7 headers in 283 bytes (0 switches on core 0)
[pid: 543|app: 0|req: 4/4] 192.168.168.1 () {48 vars in 830 bytes} [Mon Apr 27 00:21:07 2020] GET /backend/static/build/static/js/2.f684ed92.chunk.js => generated 464313 bytes in 10 msecs via sendfile() (HTTP/1.1 200) 7 headers in 302 bytes (0 switches on core 0)
[pid: 543|app: 0|req: 5/5] 192.168.168.1 () {48 vars in 836 bytes} [Mon Apr 27 00:21:07 2020] GET /backend/static/build/static/js/main.6503126e.chunk.js => generated 2903 bytes in 15 msecs via sendfile() (HTTP/1.1 200) 7 headers in 299 bytes (0 switches on core 0)
[pid: 543|app: 0|req: 6/6] 192.168.168.1 () {48 vars in 766 bytes} [Mon Apr 27 00:21:07 2020] GET /api => generated 87 bytes in 0 msecs (HTTP/1.1 200) 2 headers in 71 bytes (1 switches on core 0)
[pid: 543|app: 0|req: 7/7] 192.168.168.1 () {48 vars in 830 bytes} [Mon Apr 27 00:21:08 2020] GET /backend/static/build/favicon.ico => generated 3150 bytes in 5 msecs via sendfile() (HTTP/1.1 200) 7 headers in 286 bytes (0 switches on core 0)
[pid: 543|app: 0|req: 8/8] 192.168.168.1 () {50 vars in 878 bytes} [Mon Apr 27 00:23:15 2020] GET / => generated 2448 bytes in 34 msecs (HTTP/1.1 200) 2 headers in 81 bytes (1 switches on core 0)
[pid: 543|app: 0|req: 9/9] 192.168.168.1 () {48 vars in 836 bytes} [Mon Apr 27 00:23:15 2020] GET /backend/static/build/static/js/main.16828a0e.chunk.js => generated 2917 bytes in 7 msecs via sendfile() (HTTP/1.1 200) 7 headers in 299 bytes (0 switches on core 0)
[pid: 543|app: 0|req: 10/10] 192.168.168.1 () {48 vars in 766 bytes} [Mon Apr 27 00:23:15 2020] GET /api => generated 87 bytes in 3 msecs (HTTP/1.1 200) 2 headers in 71 bytes (1 switches on core 0)
